// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzvnixbnalxnkvykgriw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6dm5peGJuYWx4bmt2eWtncml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTk5NDYsImV4cCI6MjA3MTEzNTk0Nn0.CSFbSJ9r2oCY0Ct3NiQNv6n5dJjBrh4med3Tr3NB9L4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});